### ISSUE TITLE
Script fails when using git log w/o options

### ISSUE THREAD

**Issue by alifR999** [muiz-eddy/OTReader#1]
When using `git log > history.txt`, the script fails with the following error message:
```
Traceback (most recent call last):
  File "/Users/alif/Projects/OTReader/OTReaderV3_2.py", line 92, in <module>
    main()
  File "/Users/alif/Projects/OTReader/OTReaderV3_2.py", line 85, in main
    time_bounds = read_git_log(filename)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alif/Projects/OTReader/OTReaderV3_2.py", line 16, in read_git_log
    dt = parse_datetime(' '.join(parts[1:6]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alif/Projects/OTReader/OTReaderV3_2.py", line 6, in parse_datetime
    return datetime.datetime.strptime(date_str, "%a %b %d %Y %H:%M:%S")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '692c40b26937495dd70b6e8099b0b9ead2a15ad4' does not match format '%a %b %d %Y %H:%M:%S'
```
It seems that the script expects the user to use `git log` with a specific set of options, but these options aren't mentioned in the readme. 

Attached is the input file
[history.txt](https://github.com/user-attachments/files/16186261/history.txt)

**Comment by dulz01** [comment]
I request @alifR999 to add issues to our repo. kthxbai

**Comment by alifR999** [comment]
What, noo @dulz01. I have enough problems 😅
